### ISSUE TITLE
Latest version fails to control devices

### ISSUE THREAD

**Issue by afharo** [8none1/idealLED#18]
I just updated to the latest version and it fails to control the devices I had.

Following the recommendation, I removed the integrations and tried to set them again, but it adding the devices again fails with the following error:

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
First occurred: 21:36:57 (1 occurrences)
Last logged: 21:36:57

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ideal_led/config_flow.py", line 116, in async_step_user
    return await self.async_step_validate()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ideal_led/config_flow.py", line 155, in async_step_validate
    error = await self.toggle_light()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ideal_led/config_flow.py", line 203, in toggle_light
    raise error
  File "/config/custom_components/ideal_led/config_flow.py", line 195, in toggle_light
    await self._instance.turn_on()
  File "/config/custom_components/ideal_led/idealled.py", line 108, in _async_wrap_retry_bluetooth_connection_error
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ideal_led/idealled.py", line 484, in turn_on
    packet = COMMAND_BYTES[self._command_type]["turn_on_bytes"]
             ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: None
```

**Comment by 8none1** [comment]
Looks like this is a version of the firmware I haven't seen.  

Please enable debug logging by adding this to your `configuration.yaml`:

```yaml
logger:
  default: info
  logs:
    homeassistant.components.cloud: debug
    custom_components: debug
```

and then restart HA and attach the logs here.

I just pushed a couple of changes to main to default to a previous model rather than just failing.  That might fix this problem, but it would still be very useful to see the debug logs anyway.

**Comment by dredwater** [comment]
Just set it up today. Have similar issue, it found my lights but unable to control them form Home Assistant. The only thing working is the turn on lights.  The log do not indicate any errors as per the following when trying to select effects or change colors. (The logs seems to indicate it works, but the lights do not change.

 2025-01-11 23:34:51.779 INFO (MainThread) [custom_components.ideal_led.light] Turn on called.  kwargs: {'effect': 'Effect 09'}
2025-01-11 23:34:51.780 DEBUG (MainThread) [custom_components.ideal_led.idealled] IDL-566791: Ensure connected
2025-01-11 23:34:51.780 DEBUG (MainThread) [custom_components.ideal_led.idealled] IDL-566791: Configured disconnect from device in 60 seconds
2025-01-11 23:34:51.780 DEBUG (MainThread) [custom_components.ideal_led.idealled] Writing data to IDL-566791: b'z\xd0T\xde\x1e\x01\x0b\xfcx\xb7Ih\x80j\xf8\xbe'
2025-01-11 23:34:51.786 DEBUG (MainThread) [custom_components.ideal_led.idealled] IDL-566791: Ensure connected
2025-01-11 23:34:51.787 DEBUG (MainThread) [custom_components.ideal_led.idealled] IDL-566791: Configured disconnect from device in 60 seconds
2025-01-11 23:34:51.787 DEBUG (MainThread) [custom_components.ideal_led.idealled] Writing colour data to IDL-566791: [21, 0, 209, 0, 0, 209, 177, 0, 62, 209, 0, 0, 209, 114, 0, 125, 209, 52, 0, 209, 209, 0, 188]
2025-01-11 23:34:52.013 DEBUG (MainThread) [custom_components.ideal_led.idealled] BLE Notification raw: IDL-566791: ['0xd0', '0x7a', '0xda', '0x11', '0xae', '0x69', '0xe1', '0xb2', '0x9a', '0xf2', '0xbe', '0xae', '0x32', '0xa1', '0xed', '0x05']
2025-01-11 23:34:52.014 DEBUG (MainThread) [custom_components.ideal_led.idealled] BLE Notification decrypted: IDL-566791: ['0x07', '0x50', '0x4c', '0x41', '0x52', '0x45', '0x4f', '0x4b', '0x32', '0x07', '0x51', '0x00', '0x00', '0x00', '0x00', '0x00']

**Comment by afharo** [comment]
Apologies! I couldn't upload the logs until today (even when I captured them a few weeks ago)

[home-assistant_ideal_led_2024-12-30T22-14-40.288Z.log](https://github.com/user-attachments/files/18388534/home-assistant_ideal_led_2024-12-30T22-14-40.288Z.log)

**Comment by 8none1** [comment]
@afharo Is it this device which you are trying to control?

```text
2024-12-30 22:21:06.456 DEBUG (MainThread) [custom_components.ideal_led] Config data: {'mac': '28:2B:2D:A3:F6:C1', 'name': 'ISP-A3F6C1 (F6C1)', 'fw_version': 'TR2207R011-04'}
```

If so, it's a model `R011-04` which is indeed not one I've seen before.  It's defaulting to "Type 2" but hopefully will respond to "Type 1" commands.

To hack in a quick test for this, edit `const.py` in the `custom_components/ideal_led` directory.

Line 31 should look like this:

https://github.com/8none1/idealLED/blob/e4e632d66042b087101cbff734a84d60b33926f1/custom_components/ideal_led/const.py#L31

Add `R011-04` to the `TYPE1` array, so it looks like:

```python
COMMAND_LOOKUP = {
    "TYPE1" : ['R002-15', 'R004-01', 'R011-04'],
    "TYPE2" : ['R012-01']
```
and restart Home Assistant.

You will need to delete the device and re-add it in order for it to pick up the new device type.

Let me know if that works.  If it doesn't then we have an entirely new device type and we will need to reverse engineer the protocol.  Hope we don't have to.

**Comment by 8none1** [comment]
@dredwater please enable debug logging [as above](https://github.com/8none1/idealLED/issues/18#issuecomment-2565907668) and attach your logs in a new issue.

**Comment by dredwater** [comment]
This was my log:
_2025-01-13 17:47:06.528 DEBUG (MainThread) [custom_components.ideal_led] Config data: {'fw_version': 'TR2409R003-01', 'mac': '6C:F6:52:56:67:91', 'name': 'IDL-566791 (6791)'}
2025-01-13 17:47:06.529 DEBUG (MainThread) [custom_components.ideal_led] Config options: {}
2025-01-13 17:47:06.529 DEBUG (MainThread) [custom_components.ideal_led] Config: delay data: 60_

I modified the cost.py to:
_COMMAND_LOOKUP = {
    "TYPE1" : ['R002-15', 'R004-01', 'R003-01'],
    "TYPE2" : ['R012-01']
}_

With this change, it's now working for me.  Thanks!

**Comment by 8none1** [comment]
You know what, I'm just going to add `R011-04` to the list as well...

**Comment by 8none1** [comment]
I'm sure this will fix it, but please re-open if not.

**Comment by afharo** [comment]
> I just pushed a couple of changes to main to default to a previous model rather than just failing. That might fix this problem, but it would still be very useful to see the debug logs anyway.

Oh! I forgot to mention that after this, it worked for me. So not sure if fixing the `R011-04` model to type 1 would work since the fallback to type 2 seemed to work.

But I'll report back when I set everything back next xmas :D
